server.port: 8090

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.1:2173/postgres
    username: postgres
    password: postgres
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

CDN:
  sites:
    - youtube.com
    - akamai.com
    - netflix.com
    - facebook.com
