spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:2173/postgres
    username: postgres
    password: postgres
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
